// ! USER 
// LOGIN USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// EDIT USER
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_FAILURE = 'EDIT_FAILURE';
// REGISTER NEW USER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
// DELETE USER
export const DELETE_REQUEST = 'DELETE_REQUEST';
// ! PRODUCTS
// FIND STOCK OF ALL PRODUCTS FOR THE HOME PAGE
export const FIND_STOCK = 'FIND_STOCK';
export const SHOW_STOCK = 'SHOW_STOCK';
// FIND PRODUCT FOR THE PRODUCT PAGE
export const FIND_PRODUCT = 'FIND_PRODUCT';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
// ADD/REMOVE PRODUCT TO THE SHOPPING CART
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';